// Authored teaching policies, not real-company rules or production incidents.
const c=(id,domain,title,context,rule,input,expected,failure,risk,design,development,planning,deployment,maintenance)=>({id,domain,title,context,rule,input,expected,failure,risk,design,development,planning,deployment,maintenance});
export const domainCases=[
 c('banking','Banking','One transfer, one debit',
 'A customer transfers money between two accounts in a teaching bank. The mobile app may retry after a network timeout.',
 'A valid transfer debits and credits exactly once. Repeating the same transfer ID returns the original result without moving money again. There is no fee in this exercise.',
 'Account A starts at $1,000 and B at $200. Submit transfer T101 for $150, then retry T101.',
 'A = $850; B = $350; exactly one completed transfer T101. The combined balance remains $1,200.',
 'After the retry A = $700 and B = $500: the total is conserved, but the customer was charged twice.',
 'Duplicate money movement and incomplete debit/credit pairs can harm customers even when a success message appears.',
 'Review an atomic debit/credit operation and a unique transfer-ID record; a timeout must not cause a new transfer ID to be generated automatically.',
 'Implement the balance changes and duplicate-ID lookup; developer checks cover retries, insufficient funds and failure between debit and credit.',
 'Limit this release to same-currency internal transfers; reserve time for retry and partial-failure testing with synthetic accounts.',
 'Deploy an identifiable tested revision to the bank test environment; verify one transfer and a duplicate retry using dedicated synthetic accounts.',
 'If duplicate transfers are reported, preserve redacted transfer-ID evidence, reproduce the retry sequence and verify both the fix and other transfer paths.'),
 c('telecom','Telecommunications','Meter the prepaid data bundle correctly',
 'A prepaid subscriber buys a data bundle. Usage events can be delivered more than once by the network.',
 'This teaching tariff includes 1,000 MB with no overage charge; usage cannot reduce the remaining allowance below zero. Each usage-event ID is counted once. MB is the agreed unit.',
 'Start with 1,000 MB. Process event U17 for 250 MB twice, then event U18 for 750 MB.',
 'After both U17 deliveries, 750 MB remains. After U18, zero remains, with no extra charge.',
 'The duplicate U17 leaves only 500 MB, or the final event produces a negative allowance.',
 'Incorrect metering can remove paid service or create disputed billing; duplicate and out-of-order events matter.',
 'Define event-ID deduplication, the MB unit, and one authoritative allowance ledger shared by billing and the subscriber display.',
 'Implement allowance updates and developer checks at 0, 1 and 1,000 MB plus duplicate event IDs.',
 'Scope this release to prepaid MB bundles; agree the zero-allowance behavior and exclude roaming tariffs until their rules are supplied.',
 'Verify the deployed tariff version with synthetic usage events and confirm the subscriber display agrees with the metering ledger.',
 'Investigate disputed usage against redacted event IDs; confirm the reported defect and regress renewals and other existing bundle balances.'),
 c('insurance','Insurance','Calculate a deductible once per claim',
 'An approved property claim needs a payout calculation before payment authorization.',
 'For this exercise, payout = the approved covered loss minus a $500 deductible, with a minimum of zero and a maximum payout of $10,000. Coverage approval is supplied separately.',
 'Use approved covered losses of $300, $2,000 and $12,000 on separate synthetic claims.',
 'Payouts are $0, $1,500 and $10,000 respectively; no payout is negative.',
 'A $2,000 covered loss produces $2,000, showing that the deductible was skipped.',
 'An incorrect payout causes financial loss or underpayment; a correct formula does not establish that coverage was approved correctly.',
 'Separate coverage decision, deductible calculation and payment authorization; specify currency rounding and the payout cap explicitly.',
 'Implement the agreed order: subtract deductible, clamp at zero, then apply the payout cap; unit-check each boundary.',
 'Keep coverage decisions outside this calculation change and include deductible/cap review with the claims stakeholder.',
 'Release the tested calculation revision to the claims sandbox and compare the displayed payout with the stored authorization amount.',
 'For a reported payout mismatch, reproduce the approved input and policy version, then regress deductible and cap boundaries.'),
 c('healthcare','Healthcare','Prevent a double-booked appointment',
 'Two receptionists try to reserve the same clinician appointment slot at almost the same time.',
 'One clinician can have only one active appointment in the same slot. If two valid requests compete, one succeeds and the other receives a slot-unavailable response.',
 'Use synthetic patients P1 and P2 and one clinician slot at 10:00. Submit the two booking requests concurrently.',
 'Exactly one active appointment exists; one request succeeds and the other is rejected as unavailable.',
 'Both requests show success and two active appointments occupy the same slot.',
 'Double booking disrupts access to care; test records must be synthetic and reports must not expose patient details.',
 'Enforce slot uniqueness in the booking service/storage, rather than relying only on the browser calendar disabling the slot.',
 'Implement conflict handling and developer checks for concurrent requests, cancellation and reuse of a released slot.',
 'Agree the slot definition and cancellation rule with scheduling staff; include concurrency and privacy checks in the release scope.',
 'Verify the deployed scheduling revision in a sandbox with synthetic identities and the same concurrency case.',
 'Use redacted request IDs to investigate a conflict report; repeat the original race and regress cancellation/rebooking.'),
 c('retail','Retail and e-commerce','Reserve the last item during checkout',
 'An online shop has one unit left. Two shoppers attempt checkout before either refreshes the product page.',
 'A completed order reserves stock exactly once. Stock cannot become negative. For one remaining unit, only one of two competing orders may complete.',
 'SKU R1 has stock = 1. Submit checkout requests O1 and O2 concurrently; retry the successful request using the same order ID.',
 'One completed order, one out-of-stock response, stock = 0; the retry creates no additional order or charge.',
 'Both orders complete and stock becomes -1, or a retry creates a second order.',
 'Overselling and duplicate charges damage trust; inventory, order and payment results need to agree.',
 'Review an atomic stock reservation and order-ID deduplication; define compensation if payment fails after a reservation.',
 'Implement stock-boundary and retry checks; developer tests cover payment failure without leaving a permanent reservation.',
 'Scope the change to a single warehouse and agree reservation expiry/payment-failure behavior before creating expected outcomes.',
 'Run controlled checkouts in the deployed shop sandbox using a payment simulator and dedicated inventory.',
 'Trace overselling reports by redacted order IDs; confirm the fix and regress normal checkout, cancellation and inventory release.'),
 c('travel','Travel and hospitality','Apply the hotel cancellation cutoff',
 'A hotel booking offers free cancellation before a clearly defined cutoff in the hotel time zone.',
 'In this teaching policy, cancellation before 18:00 hotel time on the day before arrival refunds the full $200 deposit. At or after 18:00 the refund is $0.',
 'Create two equivalent synthetic bookings. Cancel one at 17:59 and the other at 18:00 hotel time on the cutoff day.',
 'The 17:59 cancellation refunds $200; the 18:00 cancellation refunds $0. Each booking becomes Cancelled.',
 'Both receive $200 because the implementation treats the cutoff as inclusive or uses the wrong time zone.',
 'Cutoff and time-zone mistakes create refund disputes; device local time must not silently determine the policy.',
 'Use the hotel time zone and an authoritative clock; separate cancellation status from the refund calculation and payment outcome.',
 'Implement the strict before-cutoff comparison; developer checks include time-zone conversion and the exact cutoff.',
 'Agree the before/at-cutoff distinction and supplied hotel time zone; keep other room-rate cancellation policies outside this release.',
 'Verify the deployed policy in a sandbox with a controllable clock and compare the recorded refund with the booking display.',
 'Investigate disputes using policy version and redacted timestamps; regress both sides of the cutoff after correcting the comparison.'),
 c('logistics','Logistics','Ignore duplicate delivery scans',
 'A courier device resends a delivery scan when it reconnects. The customer tracking page and notification service consume that event.',
 'For this exercise, scan ID D9 changes shipment S1 from Out for delivery to Delivered once and sends exactly one delivery notification. A repeated D9 is a no-op.',
 'Prepare synthetic shipment S1 as Out for delivery. Deliver D9 twice, then replay an older Out for delivery event.',
 'S1 stays Delivered; there is one delivery notification and no duplicate delivered-history entry.',
 'The customer receives two notifications, or an older scan moves the shipment back to Out for delivery.',
 'Duplicate or stale events mislead customers and support teams even when the latest scan API returns success.',
 'Define event ordering and scan-ID deduplication for the tracking state and notification consumer.',
 'Implement duplicate/stale-event handling and developer checks for replayed scans and notification retries.',
 'Agree permitted shipment transitions and the stale-event policy with operations; reserve test data for replay scenarios.',
 'Verify the deployed consumers with synthetic scans and a notification sink, checking both tracking state and notification count.',
 'Investigate by redacted shipment/scan IDs; confirm the failure sequence and regress normal delivery and return journeys.'),
 c('energy','Energy and utilities','Bill usage across tariff bands',
 'An electricity billing service calculates a monthly usage charge from two meter readings.',
 'This teaching tariff charges the first 100 kWh at $0.20/kWh and additional usage at $0.30/kWh. There are no taxes or standing charges in the exercise; decreasing readings need review, not a negative bill.',
 'Opening reading = 1,000 kWh; closing reading = 1,150 kWh. Also test a closing reading of 990.',
 '150 kWh costs $35: (100 × $0.20) + (50 × $0.30). The decreasing-reading case is flagged for review.',
 'The bill is $45 because every unit uses the upper band, or the decreasing reading produces a credit automatically.',
 'Wrong band application can affect every bill; meter rollover and replacement need separate agreed rules.',
 'Separate reading validation, usage calculation and tariff bands; store the applicable tariff version with the bill.',
 'Implement boundary checks at 99, 100 and 101 kWh and explicit rejection/review of decreasing readings under this policy.',
 'Limit the release to this tariff and agree units and rounding; do not infer rollover, taxes or other customer tariffs.',
 'Verify the deployed billing version using synthetic meter readings and compare bill lines with the independently calculated $35.',
 'For billing complaints, retain redacted readings and tariff version; confirm the fix and regress boundary usage cases.'),
 c('manufacturing','Manufacturing','Respect held stock in the bill of materials',
 'A production planner checks whether a batch can be built from usable components in inventory.',
 'Each finished unit requires three components. Components on quality hold are unavailable. A request is accepted only if usable stock covers the complete batch.',
 'There are 65 components total, with 5 on quality hold. Request 20 finished units, then test an independent request for 21 against the same reset stock.',
 'Usable stock = 60. The 20-unit request needs 60 and succeeds; the 21-unit request needs 63 and is rejected.',
 'The 21-unit request succeeds because all 65 components were counted, including held stock.',
 'Counting quarantined material can release an infeasible or inappropriate production order; batch quantity and units must be clear.',
 'Read usable inventory separately from held inventory and use the approved bill-of-materials revision in availability calculations.',
 'Implement quantity × components-per-unit and quality-hold exclusions; check exact availability and one-unit-above cases.',
 'Agree the bill of materials and hold semantics with production/quality staff; exclude substitutions until separately specified.',
 'Verify the deployed planner against synthetic inventory and confirm held components are not allocated.',
 'Investigate incorrect availability with inventory and bill-of-materials revisions; regress hold release and stock allocation.'),
 c('education','Education','Grade equal-weight answers consistently',
 'A learning platform shows a quiz score and retains it for the student result page.',
 'The exercise has five equally weighted questions. Every question counts in the denominator; a blank answer earns zero.',
 'Answer key A B C A B; submitted answers A B C D blank. Exactly the first three match.',
 'Display and store 3 of 5 correct — 60%. The blank answer remains part of the five-question total.',
 'The page shows 75% because the blank answer was excluded, or the stored result differs from the display.',
 'Incorrect grading misleads learners; displayed, calculated and stored results must describe the same attempt.',
 'Define one scoring result containing correct count, total and percentage, linked to the current attempt rather than a stale result.',
 'Implement comparison and denominator rules; developer checks include 0/5, 3/5 and 5/5 plus blanks.',
 'Agree equal weighting and blank-answer treatment with the teacher; reserve review time for result and retry behavior.',
 'Verify the deployed version with a synthetic attempt in a test environment without writing real student scores.',
 'Reproduce grading reports with synthetic answers and the relevant key/version; confirm the fix and regress other quiz topics.'),
 c('government','Government services','Block submission without a required document',
 'A permit application needs an identity-document upload before it can be submitted for review.',
 'This teaching service accepts PDF files no larger than 5,000,000 bytes. A missing, oversized or non-PDF attachment blocks submission and identifies the problem. Acceptance does not mean a permit is approved.',
 'Test no attachment, a 5,000,000-byte PDF, a 5,000,001-byte PDF and a renamed non-PDF file.',
 'Only the valid size-limit PDF can be submitted. Invalid cases remain unsubmitted with a specific validation message.',
 'An oversized or renamed non-PDF file is accepted because only the visible filename was checked.',
 'Invalid documents create processing delays and unsafe input; real identity documents must not be used as test fixtures.',
 'Validate file size/type at the service as well as the UI; keep upload acceptance separate from the application review decision.',
 'Implement server validation and developer tests for exact byte limits and content/type mismatch.',
 'Agree allowed content and precise byte limit with the service owner; use generated synthetic documents and define retention rules.',
 'Verify the deployed validation through both UI and direct service requests using synthetic files and no real applications.',
 'Investigate validation reports without exposing document contents; repeat failing inputs and regress legitimate submission.'),
 c('media','Media and subscriptions','Honor the subscription expiry boundary',
 'A streaming service grants content access only while a subscription is active.',
 'For this exercise, access is allowed strictly before the stored expiry instant in UTC and denied at or after it. The entitlement service checks the rule for each protected request.',
 'A synthetic subscription expires at 12:00:00 UTC. Request content at 11:59:59 and at 12:00:00.',
 'The first request is allowed and the second denied. Reloading the page does not restore expired access.',
 'Access remains available at expiry because only the browser menu checks the subscription.',
 'Incorrect entitlements leak paid content or deny valid customers; UI visibility alone is not access enforcement.',
 'Use an authoritative UTC clock and service-side entitlement check; specify cache-expiry behavior so stale grants cannot outlive the policy.',
 'Implement strict expiry comparison and developer checks for exact expiry, renewal and stale cached grants.',
 'Agree the expiry instant and cache rules; scope out grace periods unless the business supplies a separate policy.',
 'Verify the deployed service with synthetic subscriptions and a controllable clock, including a direct protected request.',
 'Investigate redacted entitlement/time evidence; confirm expiry fixes and regress renewal and still-active subscriptions.')
];
export const domainModules=new Set(['sdlc','requirements','manual','regression','assertions']);
export function lifecycleSteps(item){return [
 ['Planning',item.planning],['Requirements Analysis',item.rule],['Design',item.design],['Development',item.development],
 ['Testing',`${item.input} Expected: ${item.expected} Also investigate: ${item.failure}`],['Deployment',item.deployment],['Maintenance',item.maintenance]
];}
export function domainFocus(mod,card,item){
 if(mod.id==='sdlc'){
  const field={purpose:'context',planning:'planning','requirements-analysis':'rule',design:'design',development:'development',testing:'expected',deployment:'deployment',maintenance:'maintenance',feedback:'maintenance',quality:'risk',devops:'deployment',lifecycle:'rule'}[card.id]||'rule';
  return item[field];
 }
 const specific={
  'requirements/rule':`Derive the expectation from the agreed policy: ${item.expected}`,
  'requirements/acceptance':`Given these inputs, carry out the action and verify the exact outcome: ${item.input} ${item.expected}`,
  'requirements/boundaries':`Review the stated limits, invalid inputs and retry/time boundaries before accepting an observed result. In this case: ${item.failure}`,
  'manual/stlc':`Analyze this policy, plan risk-based coverage, prepare synthetic fixtures, execute the checks, and report results and unresolved risks. Key risk: ${item.risk}`,
  'manual/case':`Write a repeatable case with this setup/action: ${item.input} Expected result: ${item.expected}`,
  'manual/pattern':`Prepare a fresh synthetic fixture, perform the stated action, compare the outcome, then remove only test-created data when needed. ${item.expected}`,
  'manual/defect':`If this occurs, capture expected versus actual, reproducible steps, build/environment and redacted evidence: ${item.failure}`,
  'regression/definition':`After changing this rule, check existing supported journeys as well as the new behavior. ${item.maintenance}`,
  'regression/confirmation':`First reproduce the specific failure and verify the correction: ${item.failure} Then check connected existing behavior for side effects.`,
  'regression/impact':`Trace the policy through these components and their consumers: ${item.design}`,
  'regression/risk':`Prioritize high-consequence affected paths within available time: ${item.risk}`,
  'regression/limits':`Passing the stated fixture establishes only those tested conditions. Review other inputs, concurrency, accessibility and service failures according to risk. ${item.risk}`,
  'assertions/meaning':`Assert the business result, not just success-message visibility: ${item.expected}`,
  'assertions/state':`Reset the synthetic starting state for each independent case. A fresh browser alone does not reset this application's stored records. ${item.input}`,
  'assertions/wait':`Wait for the relevant completed business state before comparing it with: ${item.expected} An arbitrary delay is not proof of completion.`,
  'assertions/evidence':`Tie inputs, policy version, build and redacted diagnostics to the failing run. Investigate this mismatch rather than changing the expectation to hide it: ${item.failure}`
 };
 return specific[`${mod.id}/${card.id}`]||item.rule;
}
