// Authored teaching content. All website scenarios are illustrative unless explicitly marked otherwise.
const c=(id,title,idea,example,prompt,answer,source='testing',extra={})=>({id,title,idea,example,prompt,answer,...extra});
const q=(id,prompt,choices,correct,explanation,card)=>({id,prompt,choices,correct,explanation,card});
export const version='2026-09-28.1';
export const modules=[
{id:'sdlc',title:'SDLC: Software Development Lifecycle',time:'00–09 min',phase:'01 / CONTEXT',bridge:'Start with the whole system. Testing makes sense when we know why the software exists.',teacher:'Introduce the learning journey. Ask students to name the SDLC stages they already know. Use the diagram to place testing throughout the lifecycle.',cards:[
c('purpose','Software starts with a need','A useful product solves a problem for a person. Quality begins with understanding that need.','A student wants short quizzes that help them understand a lesson.','Who decides what useful means?','Users and stakeholders define the need; the team turns it into testable expectations.','sdlc'),
c('lifecycle','SDLC connects the work','The software development lifecycle connects Planning, Requirements Analysis, Design, Development, Testing, Deployment, and Maintenance. Teams revisit these activities as they learn.','A new quiz-scoring feature moves through these activities before and after release.','Does testing only happen at the end?','No. Reviews and checks can begin with requirements and continue after release.','sdlc',{flow:['Planning','Requirements Analysis','Design','Development','Testing','Deployment','Maintenance']}),
c('feedback','Feedback brings us around again','A release creates new information. Defects, student feedback, and changed needs can start another cycle.','Students report that an unanswered question receives credit. The team investigates the rule and implementation.','What should the team revisit first?','Clarify the intended scoring rule, then inspect the implementation and its checks.','sdlc',{flow:['Student feedback','Clarify rule','Change','Check again']}),
c('quality','Quality Assurance throughout the SDLC','Quality assurance builds quality into the process through reviews, standards, and prevention. Testing evaluates product behavior and supplies evidence.','A tester notices that the design does not explain what happens when an answer is missing.','Can one final test guarantee quality?','No. Quality depends on decisions and evidence throughout the work.','testing')],quiz:[q('sdlc-q1','When should the team clarify an ambiguous scoring rule?',['Only after release','As soon as it is noticed','After automating every test'],1,'Early clarification prevents building and testing the wrong behavior.','quality'),q('sdlc-q2','What connects maintenance back to planning?',['New feedback and changed needs','The font used on the page','A passing test alone'],0,'Feedback can begin another lifecycle iteration.','feedback')]},
{id:'requirements',title:'Requirements and Acceptance Criteria',time:'09–14 min',phase:'02 / REQUIREMENTS',bridge:'The lifecycle gives us context. Now we need a clear expectation before we can test.',teacher:'Ask learners to calculate 3/5. Emphasize that expected behavior must come from a requirement, not from whatever the application currently does.',cards:[
c('rule','Make the rule measurable','A testable requirement tells us what should happen under specific conditions.','For this teaching fixture, five questions have equal weight. Three correct answers must display 60%.','Where does 60% come from?','The agreed rule: 3 ÷ 5 × 100 = 60.','testing'),
c('acceptance','Acceptance criteria make agreement visible','Acceptance criteria describe conditions that the team uses to judge whether a feature behaves as intended.','When all five questions are answered and three are correct, submitting shows 60%.','Is “the score looks right” enough?','No. State the input, action, and exact expected outcome.','testing',{flow:['Known answers','Submit','Expected 60%']}),
c('boundaries','Ask about the edges','A normal case is only part of the behavior. Missing, invalid, and extreme inputs need clear rules too.','What happens if no answers are selected? Should submission be blocked or treated as zero?','Can we invent the missing-answer rule?','No. Record the open question and obtain the intended behavior before asserting it.','testing')],quiz:[q('req-q1','Which expectation is testable?',['The score is nice','The page works','Three correct out of five displays 60%'],2,'Inputs and expected output are measurable.','rule'),q('req-q2','The rule for missing answers is unclear. What next?',['Guess a rule','Clarify the requirement','Make the test always pass'],1,'An automated guess is still a guess.','boundaries')]},
{id:'manual',title:'STLC: Software Testing Lifecycle',time:'14–22 min',phase:'03 / TESTING FOUNDATIONS',bridge:'A requirement defines correctness. A test turns that expectation into a repeatable check.',teacher:'Have the class describe setup, action, and expected result. Separate the testing lifecycle from the product lifecycle.',cards:[
c('stlc','STLC organizes the testing work','The software testing lifecycle organizes analysis, planning, test design, preparation, execution, and completion. Activities can overlap and repeat.','The team analyzes the scoring rule, prepares answer data, runs checks, and reports evidence.','How is STLC related to SDLC?','It focuses on testing activities within the broader software lifecycle.','testing',{flow:['Requirement Analysis','Test Planning','Test Case Development','Test Environment Setup','Test Execution','Test Closure']}),
c('case','A test case connects cause and effect','A test case specifies setup, inputs, actions, and expected results. Someone else should be able to understand its purpose.','Open the known five-question fixture, choose three correct answers, submit, and compare the score with 60%.','Why use a known fixture?','It gives us controlled inputs and a defensible expected result.','testing'),
c('pattern','Prepare, act, assert, clean up','Prepare the starting state, perform the action, check the result, and remove data created by the test when needed.','Start a fresh quiz; select answers; submit; verify the score; reset test data.','What does “assert” mean?','Compare an observed result with the expected result and report a mismatch.','testing',{flow:['Prepare','Act','Assert','Clean up']}),
c('defect','A useful defect report is evidence','A defect report describes the environment, steps, expected result, actual result, and supporting evidence.','With the known 3/5 fixture, the page displays 80% instead of the required 60%.','Should we change the expectation to 80%?','No. Investigate the app, test data, and test against the agreed rule.','testing')],quiz:[q('manual-q1','Which part of a test compares observed and expected behavior?',['Setup','Assertion','Cleanup'],1,'An assertion checks whether evidence matches an expectation.','pattern'),q('manual-q2','A report says “it is broken.” What is missing?',['Only a new title','Reproducible steps and expected/actual results','A promise to fix it'],1,'Useful evidence allows another person to reproduce and investigate.','defect')]},
{id:'regression',title:'Regression Testing',time:'22–32 min',phase:'04 / REGRESSION',bridge:'Software changes. Now we ask whether a change damaged behavior that already worked.',teacher:'Spend time on the retesting/regression distinction. Ask students to choose neighboring quiz behaviors after a scoring change.',cards:[
c('definition','Regression testing checks for side effects','Regression testing checks whether a change has adversely affected existing behavior.','After updating score rounding, check submission, score display, and previously supported quiz cases.','Do regression checks only test the new feature?','No. Their purpose includes detecting damage to existing behavior.','testing'),
c('confirmation','Retesting checks the specific fix','Confirmation testing repeats the failing case to check that its defect was fixed. Regression testing looks for side effects elsewhere.','First confirm that 3/5 now displays 60%. Then check 0/5, 5/5, and another quiz topic.','Which activity looks beyond the original defect?','Regression testing. Both activities may be needed after a fix.','testing'),
c('impact','Follow the change through the system','Change-impact analysis identifies the behaviors and components a change could affect.','A scoring-rule change could affect the calculated percentage, the displayed result, and any stored score.','Must every feature be equally affected?','No. Trace dependencies and consider uncertainty rather than assuming equal risk.','testing',{flow:['Scoring change','Calculation','Display','Stored result']}),
c('risk','Choose coverage by risk','Prioritize checks using likelihood of failure, impact, affected dependencies, and available time.','Incorrect grading has high impact. A decorative border usually has lower impact.','Does running more tests always mean better coverage?','No. Relevant checks with meaningful assertions matter more than raw count.','testing'),
c('limits','A regression suite is not a guarantee','Passing checks provide evidence for the cases and conditions tested. They cannot prove the absence of all defects.','The score checks pass, but a screen-reader user may still be unable to submit the quiz.','What should complement the suite?','Exploration, accessibility checks, reviews, and other testing selected for the risks.','testing')],quiz:[q('reg-q1','After fixing one scoring defect, you test another quiz topic. This is mainly…',['Regression testing','Changing the requirement','Writing a release announcement'],0,'You are checking for side effects in existing behavior.','confirmation'),q('reg-q2','Which check deserves priority after a scoring-rule change?',['Header color','Percentage calculation for known inputs','Unrelated marketing copy'],1,'Prioritize affected behavior and impact.','risk'),q('reg-q3','All selected regression checks pass. What can you conclude?',['There are no defects','The selected checks passed under their tested conditions','Manual testing is unnecessary'],1,'Coverage and environmental limits still apply.','limits')]},
{id:'automation',title:'Test Automation',time:'32–42 min',phase:'05 / AUTOMATION',bridge:'Regression creates repeatable work. Automation can help us perform selected checks consistently.',teacher:'Ask students to sort three candidates: repeated scoring calculation, an unstable experimental page, and an open-ended usability question. Discuss the cost of maintenance.',cards:[
c('why','Automation repeats explicit instructions','Test automation uses software to prepare, act, and check outcomes. People still decide the purpose and expected behavior.','A runner repeatedly submits known answers and compares the result with the agreed score.','Does automation decide what quality means?','No. It executes checks designed around human-understood requirements and risks.','testing',{flow:['Requirement','Test code','Runner','Evidence']}),
c('candidate','Start with a valuable repeatable check','Good candidates often have stable behavior, controllable data, frequent execution, and clear expected results.','A known scoring calculation is repeated on each release and has an exact expected value.','What makes it a useful first candidate?','Repeatability, clear expectations, and meaningful risk reduction.','testing'),
c('maintenance','Automation needs maintenance','Tests may need updates when requirements, interfaces, or environments change. Unreviewed tests can become misleading.','A renamed button can break a locator even when the scoring rule is unchanged.','Should every failure be treated as a product defect?','No. Investigate the product, test, data, and environment.','testing'),
c('explore','Keep human exploration','Exploratory testing combines learning, design, and execution. It helps discover questions that scripted checks did not anticipate.','A tester tries unusual navigation while deciding whether the quiz flow is understandable.','Can a fixed script replace all exploration?','No. Scripts check known expectations; exploration can reveal new risks.','testing')],quiz:[q('auto-q1','Which is the strongest first automation candidate?',['A frequent check with a precise expected result','A feature whose behavior nobody understands','An undefined usability preference'],0,'Clear, valuable, repeatable checks are a practical starting point.','candidate'),q('auto-q2','A test fails after a button label changes. What should you do?',['Delete all assertions','Investigate whether the app or test needs correction','Assume the score calculation failed'],1,'A test failure is a signal to investigate.','maintenance')]},
{id:'assertions',title:'Assertions and Test Evidence',time:'42–52 min',phase:'06 / EVIDENCE',bridge:'Repeating a check is useful only when it checks the right thing and starts from a reliable state.',teacher:'Contrast “score exists” with “score equals 60%.” Ask why a passing test could miss an incorrect score. Break from minute 52 to 57.',cards:[
c('meaning','Check the value, not just its presence','A visible result can still be wrong. The assertion must match the requirement.','The page shows 80%. A visibility check passes; an exact 60% check fails.','Which assertion catches this defect?','The exact expected value, for the known fixture.','assert',{code:"await expect(score).toHaveText('60%');"}),
c('state','Control the starting state','Independent tests prepare the state they need. Browser isolation alone does not reset shared backend data.','A previous run leaves an old score. The next run must not mistake it for its new result.','Does opening a fresh browser clear the database?','No. Application data needs its own setup or cleanup strategy.','pw'),
c('wait','Wait for a condition','A condition-based wait responds to the application becoming ready. A fixed delay can be too short or unnecessarily long.','Wait until the result contains the expected text instead of sleeping for an arbitrary five seconds.','Why can a fixed delay be unreliable?','Application and network timing vary. A condition describes what ready means.','assert'),
c('evidence','Read a failure before changing the test','Logs, screenshots, traces, and input data help explain a mismatch. Evidence should be tied to the run that produced it.','Expected 60%, observed 80%: examine the fixture and result rather than accepting the observed number.','Is changing expected to actual a fix?','Only if the requirement legitimately changed and the new expectation was reviewed.','pw')],quiz:[q('assert-q1','The wrong score is visible. Which assertion detects it?',['is visible','equals the required score','page has a title'],1,'Presence alone does not validate the business result.','meaning'),q('assert-q2','What should replace an arbitrary wait when possible?',['A longer arbitrary wait','A wait for the needed condition','No synchronization'],1,'Condition-based waiting follows application readiness.','wait')]},
{id:'tools',title:'Automation Tools',time:'57–67 min',phase:'07 / TOOLCHAIN',bridge:'We have a test design. Now place the tools around it without confusing tools with the testing strategy.',teacher:'Give each tool a role. This is awareness and preparation, not an installation workshop. Keep the focus on the upcoming browser and API walkthroughs.',cards:[
c('playwright','Playwright drives browser interactions','Playwright can automate browsers and provides a test runner with assertions and diagnostic tools.','A browser check selects answers, submits, and inspects the visible score.','What layer does this example observe?','The user-facing browser interaction and displayed result.','pw'),
c('cypress','Cypress supports web testing','Cypress supports end-to-end and component testing for web applications. Its programming model differs from Playwright.','A Cypress check could exercise the same quiz journey with its own commands.','Do identical tool goals imply identical syntax?','No. Learn the execution model of the chosen tool.','cy'),
c('selenium','Selenium automates browser control','Selenium WebDriver controls browsers through bindings in several programming languages. A test framework supplies the surrounding test structure.','A Java test can use WebDriver to interact with a quiz form.','Is Selenium limited to Java?','No. Selenium provides multiple language bindings.','sel'),
c('node','Node.js runs JavaScript outside the browser','JavaScript describes program behavior. Node.js supplies a runtime outside the browser, including for many test tools.','A Playwright test file is executed by its Node-based tooling, which controls a browser.','Is Node.js the browser page?','No. It is a separate runtime used by the tooling.','pw,npm'),
c('npm','npm commands run project-defined tasks','npm manages JavaScript packages. An npm script is a named command defined in a project’s package.json.','npm test only does what that project has configured for its test script.','Does npm test automatically choose the right tests?','No. The project must define its dependencies and commands.','npm'),
c('pipeline','A pipeline runs the prepared checks','Git records changes. Jenkins can orchestrate a pipeline that installs dependencies, runs checks, and retains evidence.','A change triggers a configured job that runs the regression suite and reports failures.','Does Jenkins write the assertions for us?','No. It executes the configured process.','jenkins',{flow:['Change','Install','Run checks','Report']}),
c('environment','The environment is part of the test','Docker can package a runtime; Kubernetes can orchestrate containers; cloud services such as AWS host infrastructure. These are distinct roles.','A test runner needs the correct application URL, configuration, and controlled data wherever it runs.','Does putting a test in the cloud make it correct?','No. Requirements, assertions, data, and configuration still determine its value.','jenkins')],quiz:[q('tools-q1','What determines what npm test executes?',['The project’s script configuration','The browser title','A student’s score'],0,'npm runs the command configured by the project.','npm'),q('tools-q2','What is Jenkins doing in this journey?',['Defining the scoring rule','Orchestrating configured build and test work','Replacing browser locators'],1,'The pipeline runs the steps and retains evidence.','pipeline')]},
{id:'ai',title:'AI-Assisted Testing',time:'67–79 min',phase:'08 / AI ASSISTANCE',bridge:'Tools execute checks. AI can help draft them, while people remain responsible for correctness.',teacher:'Ask what context a Copilot prompt needs. Compare a weak draft assertion with the actual requirement. Do not present authored text as captured AI output.',cards:[
c('llm','An LLM generates language from patterns','A large language model generates text using patterns learned during training and the context it receives. Plausible output can still be incorrect.','An assistant may invent a quiz button name that does not exist in the app.','Does confident wording prove correctness?','No. Verify generated details against the actual application and requirements.','ai'),
c('copilot','Copilot is an assistant, not the authority','GitHub Copilot can assist with code and tests. Product capabilities and organizational permissions depend on the configured product and plan.','Ask for candidate regression checks, then review each against the scoring requirement.','Who accepts the proposed assertion?','A person responsible for reviewing the test and its intended behavior.','ai'),
c('lms','LMS and LLM mean different things','An LMS is a learning management system for organizing learning and tracking participation. An LLM is a language model.','An LMS can deliver a course; an AI assistant can help draft reviewed learning or testing material.','Is an LMS itself a language model?','No. They serve different roles.','lms,ai'),
c('prompt','Give the assistant a testable contract','Supply the requirement, real interface details, fixture, and constraints. Ask it to flag missing information.','“Three correct answers out of five must display 60%. Use these actual controls. Do not invent selectors.”','What should happen when a selector is unknown?','Inspect the interface or ask for the missing detail before treating the draft as runnable.','ai'),
c('review','Review before running','Check generated selectors, assertions, data handling, and assumptions. Use only data permitted by your organization.','An authored illustrative draft checks that a score is visible. The reviewer replaces it with the required value check.','Why is visibility too weak here?','A wrong score can still be visible.','ai,assert',{flow:['Provide context','Draft','Review','Run','Inspect evidence']})],quiz:[q('ai-q1','AI invents a selector. What should happen next?',['Run it as trusted code','Verify against the actual interface','Change the app blindly'],1,'Generated interface details require verification.','prompt'),q('ai-q2','Which statement is correct?',['An LMS and an LLM are identical','An LMS organizes learning; an LLM generates language','AI output is always a reliable test oracle'],1,'Separate the learning platform from the language model.','lms')]},
{id:'ui',title:'UI Automation',time:'79–92 min',phase:'09 / UI AUTOMATION',bridge:'Bring the requirement, fixture, runner, and assertion together at the browser layer.',teacher:'Walk through each micro-card. These are code-reading examples, not a live lab. A later hands-on session must use implemented controls on our website.',cards:[
c('ui-layer','UI tests observe the user-facing flow','A UI test interacts with the page and checks observable outcomes such as displayed text or navigation.','A student selects answers, presses Submit, and reads a score.','What can this catch beyond a direct API check?','Problems in interactions, rendering, or how the page connects to the service.','pw',{flow:['Select answers','Press Submit','Read score']}),
c('locator','A locator identifies the intended element','Prefer meaningful roles, labels, or agreed test IDs over fragile layout-dependent selectors.','The following assumes a real button with the accessible name Submit. It is not a verified selector for the current site.','What must we verify before running this?','That the actual application exposes the intended control with this role and name.','loc',{code:"await page.getByRole('button', { name: 'Submit' }).click();"}),
c('fixture','The fixture makes the expected score known','Control the answer key and selected answers before asserting the result.','Teaching key: A B C A B. Submitted answers: A B C D E. Exactly three match.','What score should equal weighting produce?','60%. Three correct answers divided by five questions.','testing'),
c('ui-assert','Assert the visible business result','A browser assertion should check the expected student-visible outcome after the action.','This excerpt assumes the fixture, navigation, and a quiz-score test ID have already been prepared.','Does this single check prove every quiz works?','No. It proves only the checked outcome for this run and fixture.','assert',{code:"await expect(page.getByTestId('quiz-score'))\n  .toHaveText('60%');"}),
c('diagnose','A failure is a question to investigate','Compare expected and observed results, then inspect the run evidence to locate the cause.','Illustrative result: expected 60%, actual 80%. This is authored teaching data, not an executed test report.','Where might the cause be?','The product, fixture, test logic, or environment. Evidence helps distinguish them.','pw')],quiz:[q('ui-q1','What should a UI score assertion compare?',['Only that text exists','Displayed value against the known expected value','The test filename'],1,'The visible result must match the requirement.','ui-assert'),q('ui-q2','Can the sample selector be assumed to exist on our site?',['Yes, because it looks plausible','No, inspect the real interface first','Only if AI wrote it'],1,'The snippet is explicitly illustrative until wired to real controls.','locator')]},
{id:'api',title:'API Automation',time:'92–105 min',phase:'10 / API AUTOMATION',bridge:'The browser shows a result. An API check inspects the service response directly. Both connect back to the same requirement.',teacher:'Read the hypothetical contract and Karate excerpt. Close with the UI/API distinction. Reserve minutes 105–120 for open questions. No live endpoint is implied.',cards:[
c('api-layer','An API is an interface between programs','A client sends a request; a service processes it and returns a response according to its contract.','In a proposed architecture, the browser sends quiz answers to a scoring service. That service has not been implemented by this lesson.','Does a service response prove the page rendered correctly?','No. A direct API check bypasses the browser rendering.','http',{flow:['Browser / client','Request','Quiz service','Response']}),
c('request','The request carries inputs','A method, path, headers, and body describe what the client is asking the service to do.','Hypothetical contract: POST /quiz/submit with a quiz ID and five answer choices.','Is this a live endpoint on our site?','No. It is a proposed teaching example. Hands-on work requires building and testing the real endpoint.','http',{code:'POST /quiz/submit\n{"quizId":"demo-5","answers":["A","B","C","D","E"]}'}),
c('response','Check the business data','A successful HTTP status alone does not establish that the calculation is correct. Check required fields and values too.','For the known key A B C A B, the hypothetical response has correct: 3, total: 5, percentage: 60.','Can HTTP 200 accompany an incorrect percentage?','Yes. The business result needs its own assertions.','http',{code:'200 OK\n{"correct":3,"total":5,"percentage":60}'}),
c('karate','Karate expresses API expectations','Karate supports request setup and response assertions. The service URL, fixture, and environment must exist before an excerpt can run.','This conceptual excerpt checks the chosen status and score. HTTP 200 is this exercise’s contract, not a universal rule for POST.','What is baseUrl here?','A configured service address. This lesson does not supply a live service.','karate',{code:"Given url baseUrl\nAnd path 'quiz', 'submit'\nAnd request { quizId: 'demo-5', answers: ['A','B','C','D','E'] }\nWhen method post\nThen status 200\nAnd match response.percentage == 60"}),
c('combine','Combine evidence from both layers','UI checks validate student-visible interactions. API checks validate direct service behavior. Select both according to risk.','A correct service response can still be displayed incorrectly; a UI can also show a stubbed result without exercising the real service.','What must a test report make clear?','Which layer and dependencies were exercised, which were simulated, and what was actually observed.','pw,karate',{flow:['Requirement','UI evidence','API evidence','Risk judgment']})],quiz:[q('api-q1','HTTP 200 is returned with percentage 80 for the 3/5 fixture. What is true?',['Everything passed','The business result violates the expected contract','The UI must be correct'],1,'Status and business data are separate assertions.','response'),q('api-q2','What must happen before this becomes hands-on on our website?',['Rename the slides','Implement the endpoint and connect real tests','Pretend the sample was executed'],1,'The real website, API, fixture, and runnable tests must exist.','request'),q('api-q3','Which describes the whole journey?',['Choose a tool, then invent expectations','Define behavior, design checks, select regression coverage, automate and review evidence','Passing tests prove no defects'],1,'The requirement anchors both UI and API evidence.','combine')]}
];
const toolCards=modules.find(m=>m.id==='tools').cards;
const sdlcStages=[
['planning','Planning','Establish purpose, scope, feasibility, resources, and risks before committing to a software change.','Decide which quiz feature will help students and what can be delivered within the available time.','What does planning establish?','Why the change matters, what is in scope, and whether it is feasible.'],
['requirements-analysis','Requirements Analysis','Understand, document, and validate the required behavior and constraints. Resolve ambiguity with stakeholders.','Agree that three correct answers out of five equally weighted questions must display 60%.','Where does the expected result come from?','The validated requirement, not whatever value the current program produces.'],
['design','Design','Define the architecture, data, interfaces, and user experience needed to satisfy the requirements.','Plan the quiz form, answer data, scoring interface, and feedback presentation.','What connects requirements to implementation?','The design explains how the required behavior will be built.'],
['development','Development','Implement the agreed design in code and perform developer checks.','Build answer selection and scoring behavior against the agreed rule.','Does coding replace requirement analysis?','No. Code implements the understood requirements and design.'],
['testing','Testing','Evaluate software against requirements, identify defects, and provide evidence about risk. Testing activities can start before coding.','Check known scores, missing inputs, and affected existing quiz behavior.','Is all quality assurance confined to this stage?','No. Quality assurance and reviews occur throughout the lifecycle.'],
['deployment','Deployment','Release software to its intended environment using a controlled, repeatable process.','Publish an identifiable tested version of the quiz feature and verify it in that environment.','Is a local passing test the same as deployment?','No. Deployment makes a version available in the intended environment and needs its own verification.'],
['maintenance','Maintenance','Support released software, correct defects, and adapt it to changed needs.','Fix a reported scoring defect, reassess affected behavior, and release a verified correction.','Can maintenance lead back to requirements?','Yes. Feedback and changed needs can begin another iteration.']
];
modules[0].cards.splice(2,0,...sdlcStages.map(([id,title,idea,example,prompt,answer])=>c(id,title,idea,example,prompt,answer)),c('devops','SDLC in DevOps','DevOps supports collaboration, automation, and continuous feedback. The lifecycle activities remain, but can run in shorter, overlapping iterations.','A small scoring change still needs requirements, design, development, testing, deployment, and maintenance feedback.','Does DevOps require containers or remove testing?','No. Containers are optional environment tooling. QA and testing remain essential across the lifecycle.'));
modules[0].bridge='Quality assurance spans the entire Software Development Lifecycle. Learn the standard stage names, then connect each stage to the quiz website.';
modules[0].teacher='Use the lifecycle overview for the class recap. Open individual stage cards when clarification is needed; they also support student review. Preserve the stage names. Plain-language explanations sit underneath them. Explain that DevOps repeats and overlaps lifecycle activities; containers are optional.';
toolCards.splice(toolCards.findIndex(x=>x.id==='node'),0,c('javascript','JavaScript expresses the test steps','JavaScript is a programming language. Variables hold data, functions organize actions, and conditions express decisions.','A test uses a variable for the expected score and calls functions to interact with controls.','Is JavaScript the same language as Java?','No. They are distinct languages.','js'));
toolCards.splice(toolCards.findIndex(x=>x.id==='pipeline'),0,c('git','Git records changes over time','Version control records revisions and helps people compare and collaborate on changes.','A commit contains a scoring-rule change and its updated regression test.','Does a commit prove the tests passed?','No. Test results are separate evidence associated with a revision.','git'));
toolCards.splice(toolCards.findIndex(x=>x.id==='environment'),1,
c('docker','Docker packages an execution environment','A container packages an application with needed runtime dependencies. Configuration and persistent data still need explicit handling.','A team runs its test runner in a container with a known runtime.','Does a container automatically reset application data?','No. Data setup and cleanup remain explicit responsibilities.','docker'),
c('kubernetes','Kubernetes manages container workloads','Kubernetes orchestrates containerized applications, including deployment and scaling. It does not decide whether business behavior is correct.','A quiz service might run in a Kubernetes cluster while a test runner calls its address.','Does orchestration replace testing?','No. It manages workloads; tests still check behavior.','k8s'),
c('cloud','Cloud infrastructure hosts the environment','Cloud providers such as AWS offer computing, storage, and networking services. A test needs the correct target and configuration.','A staging quiz service could run in AWS. Tests must target staging with controlled data.','Does cloud hosting make a test correct?','No. Requirements, assertions, data, and configuration determine test value.','cloud'));
