import {openVisualLesson} from './visual-lessons.js';
import {modules as library,version} from './learning-content.js';
import {classOne} from './lesson-context.js';
import {examplePanel,bindExamples} from './lesson-examples.js';
const guided=new URLSearchParams(location.search).get('class')==='1';
const modules=guided?library.map(mod=>{const plan=classOne[mod.id],q=plan.question;return {...mod,cards:plan.cards.map(id=>mod.cards.find(card=>card.id===id)),quiz:[{id:`class1-${mod.id}`,prompt:q[0],choices:q[1],correct:q[2],explanation:q[3],card:q[4]}]};}):library;
const $=s=>document.querySelector(s), key=`mqa-learning-${version}${guided?"-class1":""}`;
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
if(typeof saved!=='object'||Array.isArray(saved)) saved={};
let m=0,c=0,mode='learn',question=0,answers=[];
const escape=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));}catch{$('#overall').textContent='Progress storage unavailable. You can still use all lessons.';}}
function route(){const [mid,cid]=location.hash.slice(1).split('/');const i=modules.findIndex(x=>x.id===mid);m=i<0?0:i;c=Math.max(0,modules[m].cards.findIndex(x=>x.id===cid));mode='learn';render();}
function navigate(mi,ci=0){const hash=`#${modules[mi].id}/${modules[mi].cards[ci].id}`;if(location.hash===hash){m=mi;c=ci;mode='learn';render();}else location.hash=hash;}
function flow(items,title){return `<ol class="process-flow" aria-label="${escape(title)}">${items.map(x=>`<li>${escape(x)}</li>`).join('')}</ol>`;}
function renderNav(){const count=modules.filter(x=>Number.isInteger(saved[x.id]?.score)).length;$('#modules').innerHTML=modules.map((x,i)=>`<button data-module="${i}" ${i===m?'aria-current="step"':''}><b>${String(i+1).padStart(2,'0')}</b><span>${escape(x.title)}${Number.isInteger(saved[x.id]?.score)?' ✓':''}</span></button>`).join('');$('#overall').textContent=`${count} / ${modules.length} section quizzes completed`;$('#modules').querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(Number(b.dataset.module)));}
function render(){const mod=modules[m];$('#class-close').hidden=true;const origin=new URLSearchParams(location.search).get('topic')||({sdlc:'SDLC',manual:'STLC',requirements:'Requirements',regression:'Testing Types',automation:'Testing Types',assertions:'Test Artifacts',tools:'Jenkins',ai:'SDLC',ui:'Testing Types',api:'Testing Types'}[mod.id]);document.querySelectorAll('.quiz-return-link').forEach(a=>a.href='index.html?topic='+encodeURIComponent(origin));document.querySelector('#return-to-quiz').textContent='← Return to '+origin+' quiz & flashcards';renderNav();$('#phase').textContent=mod.phase;$('#module-title').textContent=mod.title;$('#time').textContent=mod.time;$('#bridge').textContent=mod.bridge;$('#teacher').textContent=guided?`Class 1: ${classOne[mod.id].takeaway} Use the analogy, invite a learner experience, connect it to the illustrative case, and finish with one quick check. ${classOne[mod.id].later}`:mod.teacher;
$('#class-takeaway').textContent=classOne[mod.id].takeaway;
$('#class-later').textContent=classOne[mod.id].later;
const fullURL=new URL(location.href);fullURL.searchParams.delete('class');$('#library-link').href=fullURL.pathname+fullURL.search+fullURL.hash;
$('#learn-mode').setAttribute('aria-pressed',mode==='learn');$('#quiz-mode').setAttribute('aria-pressed',mode==='quiz');$('.controls').hidden=mode==='quiz';if(mode==='quiz'){renderQuiz();return;}const card=mod.cards[c];$('#stage').innerHTML=`<article class="micro-card" aria-label="Concept ${c+1} of ${mod.cards.length}"><div class="card-meta"><span>Concept ${String(c+1).padStart(2,'0')}</span><span>${c+1} / ${mod.cards.length}</span></div><h3 tabindex="-1">${escape(card.title)}</h3><p class="idea">${escape(card.idea)}</p>${card.flow?flow(card.flow,card.title):''}${examplePanel(mod,card)}${card.code?`${guided?'<details class="code-preview"><summary>Optional code preview · detailed practice comes later</summary>':''}<pre aria-label="Illustrative code excerpt"><code>${escape(card.code)}</code></pre>${guided?'</details>':''}`:''}<div class="recall"><p><strong>Recall it</strong> · ${escape(card.prompt)}</p><button id="reveal" aria-expanded="false">Reveal answer</button><p id="recall-answer" class="answer" hidden>${escape(card.answer)}</p></div><button id="open-visual" class="visual-open">Open study material →</button></article>`;bindExamples($('#stage'),mod,card);
$('#open-visual').onclick=()=>openVisualLesson(library.find(item=>item.id===mod.id),card,$('#open-visual'));$('#reveal').onclick=()=>{const open=$('#recall-answer').hidden;$('#recall-answer').hidden=!open;$('#reveal').setAttribute('aria-expanded',open);$('#reveal').textContent=open?'Hide answer':'Reveal answer';};$('#prev').disabled=c===0;$('#next').textContent=c===mod.cards.length-1?guided?'Quick recap check →':'Take mini quiz →':'Next concept →';$('#dots').innerHTML=mod.cards.map((x,i)=>`<button data-card="${i}" aria-label="Concept ${i+1}: ${escape(x.title)}" aria-current="${i===c}">${i+1}</button>`).join('');$('#dots').querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(m,Number(b.dataset.card)));}
function startQuiz(){mode='quiz';question=0;answers=[];render();}
function renderQuiz(){const mod=modules[m], qs=mod.quiz;if(question>=qs.length){$('#class-close').hidden=!(guided&&m===modules.length-1);const score=answers.filter((a,i)=>a===qs[i].correct).length;saved[mod.id]={score,total:qs.length};persist();renderNav();$('#stage').innerHTML=`<article class="micro-card"><div class="card-meta">Section complete · practice result</div><h3>${score} / ${qs.length} connections made</h3><p class="idea">${score===qs.length?'You connected the key ideas. Continue the journey.':'Revisit the concepts below, then try again.'}</p>${qs.map((q,i)=>`<p>${answers[i]===q.correct?'✓':'↺'} ${escape(q.explanation)} <button class="review" data-card="${escape(q.card)}">Review concept</button></p>`).join('')}<button id="retry">Try quiz again</button> <button id="continue" class="primary">${m<modules.length-1?'Next section →':'Return to the journey'}</button><p class="small">Self-check only. This result stays in this browser and is not a submitted grade.</p></article>`;$('#retry').onclick=startQuiz;$('#continue').onclick=()=>navigate(m<modules.length-1?m+1:0);$('.micro-card').querySelectorAll('.review').forEach(b=>b.onclick=()=>navigate(m,mod.cards.findIndex(x=>x.id===b.dataset.card)));return;}const item=qs[question];$('#stage').innerHTML=`<article class="micro-card"><div class="card-meta"><span>Mini quiz</span><span>Question ${question+1} / ${qs.length}</span></div><form id="question-form"><fieldset><legend>${escape(item.prompt)}</legend>${item.choices.map((v,i)=>`<label class="choice"><input required type="radio" name="choice" value="${i}"><span>${escape(v)}</span></label>`).join('')}</fieldset><button class="primary" id="check">Check answer</button><div id="feedback" role="status"></div></form><button id="advance" hidden>${question===qs.length-1?'See my result':'Next question →'}</button></article>`;$('#question-form').onsubmit=e=>{e.preventDefault();const selected=$('input[name=choice]:checked');if(!selected)return;const n=Number(selected.value);answers[question]=n;$('#feedback').className='feedback';$('#feedback').textContent=`${n===item.correct?'Correct.':'Not quite.'} ${item.explanation}`;$('#question-form').querySelector('fieldset').disabled=true;$('#check').hidden=true;$('#advance').hidden=false;$('#advance').focus();};$('#advance').onclick=()=>{question++;renderQuiz();};}
$('#prev').onclick=()=>{if(c>0)navigate(m,c-1);};$('#next').onclick=()=>{if(c<modules[m].cards.length-1)navigate(m,c+1);else startQuiz();};$('#learn-mode').onclick=()=>{mode='learn';render();};$('#quiz-mode').onclick=startQuiz;$('#guide-toggle').onclick=()=>{$('#guide').hidden=!$('#guide').hidden;$('#guide-toggle').setAttribute('aria-expanded',!$('#guide').hidden);};$('#reset').onclick=()=>{if(confirm('Reset all section quiz results stored in this browser?')){saved={};persist();renderNav();}};document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||mode!=='learn'||/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName))return;if(e.key==='ArrowRight'&&c<modules[m].cards.length-1){e.preventDefault();navigate(m,c+1);}if(e.key==='ArrowLeft'&&c>0){e.preventDefault();navigate(m,c-1);}});const overviewURL=new URL(location.href);overviewURL.searchParams.set('class','1');overviewURL.hash='sdlc/lifecycle';
$('#class-one-link').href=overviewURL.pathname+overviewURL.search+overviewURL.hash;
const libraryURL=new URL(location.href);libraryURL.searchParams.delete('class');
$('#library-link').href=libraryURL.pathname+libraryURL.search+libraryURL.hash;
$('#class-one-link').setAttribute('aria-current',guided?'page':'false');
$('#library-link').setAttribute('aria-current',guided?'false':'page');
$('#class-mode-label').textContent=guided?'Class 1 guided recap · 22 focus cards · 10 quick checks':'Full concept library · 58 cards · optional deeper review';
$('#class-session-note').textContent=guided?'Recap the foundations, preview the tools, and connect UI with API automation. Recognize the purpose today; build detailed skills in the relevant course modules.':'Use the guided Class 1 path for the two-hour session. The full library keeps extra concepts available for questions and later review.';
$('#class-schedule').innerHTML=library.map((mod,i)=>`<li><a href="?class=1#${mod.id}/${classOne[mod.id].cards[0]}"><b>${escape(mod.time)}</b> ${escape(mod.title)}</a><span>${escape(classOne[mod.id].takeaway)}</span></li>${i===5?'<li class="schedule-pause"><b>52–57 min</b> Five-minute break</li>':''}`).join('')+'<li class="schedule-pause"><b>105–120 min</b> Student questions, connect the journey, and close</li>';
window.addEventListener('hashchange',route);route();
