// Authored analogies and illustrative workplace cases, not reported incidents.
const entry = (analogy, connection, limit, situation, check, impact) => ({analogy, connection, limit, situation, check, impact});
export const examples = {
  'sdlc/purpose': entry('A bus route is useful when it takes people where they need to go.', 'Start with the learner need before choosing a feature.', 'Software needs still require evidence from users.', 'An academy adds short practice quizzes for learners who have only ten minutes.', 'Ask what learners need to practice and how feedback will help.', 'A polished feature can still solve the wrong problem.'),
  'sdlc/lifecycle': entry('Opening a cafe involves a plan, customer needs, a layout, preparation, checks, opening day, and ongoing improvements.', 'These activities help connect the SDLC stages to a familiar project.', 'Software stages can overlap and repeat; this is not a rule that all work happens once in sequence.', 'A team adds a new quiz-scoring rule.', 'Follow the rule through requirements, design, code, tests, release, and learner feedback.', 'Everyone can see where quality decisions are made.'),
  'sdlc/planning': entry('Before a trip, agree on the destination, budget, time, and likely obstacles.', 'Planning establishes scope, feasibility, resources, and risks.', 'A software plan changes as evidence arrives.', 'A team has one week to improve quiz feedback.', 'Agree which feedback changes fit and what is outside this release.', 'A clear scope helps avoid unfinished or untested work.'),
  'sdlc/requirements-analysis': entry('A tailor checks measurements and the requested fit before cutting fabric.', 'Clarify the required behavior before building or testing it.', 'User needs may need several conversations, not one measurement.', 'A teacher says unanswered quiz questions should be handled fairly.', 'Resolve whether to block submission or score missing answers as incorrect.', 'An ambiguous rule creates conflicting implementations and tests.'),
  'sdlc/design': entry('A floor plan shows how rooms, doors, and utilities will connect before construction.', 'Software design connects screens, data, and interfaces to requirements.', 'Software designs can evolve in small iterations.', 'The team designs answer selection, submission, and score display.', 'Review where the scoring rule lives and how errors reach the learner.', 'Interface gaps can be found before coding.'),
  'sdlc/development': entry('A cook turns an agreed recipe into a meal using the specified ingredients.', 'Development turns the design into working behavior.', 'Code still needs reviews and checks; following instructions is not proof of correctness.', 'A developer implements the percentage calculation.', 'Compare the code and developer checks with known answer sets.', 'Small calculation errors can affect every learner.'),
  'sdlc/testing': entry('Before opening a shop, walk through selecting an item, paying, and receiving a receipt.', 'Testing compares observable behavior with expectations.', 'A walkthrough is only one test; quality also depends on earlier reviews.', 'A team evaluates a new quiz submission flow.', 'Try expected scores, missing inputs, and affected existing behavior.', 'The evidence reveals defects and remaining uncertainty.'),
  'sdlc/deployment': entry('A restaurant introduces a checked menu in the dining room, where customers actually use it.', 'Deployment makes a selected version available in its intended environment.', 'A release needs technical controls and verification beyond an opening announcement.', 'The scoring update moves from a test environment to the student site.', 'Identify the release and verify its critical behavior after release.', 'Local success alone does not show what students received.'),
  'sdlc/maintenance': entry('After a bicycle repair, regular checks and feedback guide later adjustments.', 'Maintenance supports and adapts released software.', 'Software changes can also introduce new requirements.', 'Learners report confusing feedback for unanswered questions.', 'Investigate the report, clarify the rule, and verify the correction.', 'Released software needs continued attention.'),
  'sdlc/devops': entry('A kitchen can improve one dish at a time while cooks and servers share feedback.', 'Smaller changes and fast feedback connect development and operations.', 'This analogy does not make containers mandatory or remove SDLC activities.', 'A team releases small quiz improvements frequently.', 'Keep requirement checks, test evidence, deployment checks, and feedback in each iteration.', 'Shorter cycles still need quality assurance.'),
  'sdlc/feedback': entry('A navigation route changes when a road closure is reported.', 'New evidence can send the team back to earlier decisions.', 'Feedback must be investigated rather than accepted without context.', 'Several learners misunderstand the score summary.', 'Revisit the intended message and observe the current display.', 'Feedback helps choose the next useful change.'),
  'sdlc/quality': entry('A restaurant prevents mistakes through clear recipes, training, and ingredient checks as well as tasting food.', 'QA builds quality into the process; testing supplies product evidence.', 'Prevention reduces risk but does not eliminate all defects.', 'A tester notices that the scoring design omits missing answers.', 'Raise the gap before implementation and agree acceptance criteria.', 'Early clarification avoids building the wrong behavior.'),
  'requirements/rule': entry('A shelf label saying $10 gives a clearer checkout expectation than a label saying affordable.', 'A measurable requirement gives a test a defensible expected result.', 'Real requirements also include context and constraints.', 'An illustrative quiz has five equally weighted questions.', 'Agree that three correct answers must display 60%.', 'A clear rule allows people and tests to judge the same result.'),
  'requirements/acceptance': entry('A delivery agreement specifies the parcel, address, and delivery window.', 'Acceptance criteria describe conditions for judging the result.', 'Criteria are selected agreements, not every possible quality check.', 'A team prepares to accept the scoring feature.', 'Specify the known answers, submission action, and expected display.', 'The team can evaluate completion consistently.'),
  'requirements/boundaries': entry('Before sharing a bill, ask what happens if one person leaves without paying.', 'Boundary and missing-input questions expose incomplete rules.', 'A convenient answer is not automatically the agreed product behavior.', 'A learner submits a quiz without answering anything.', 'Clarify the intended response before encoding an assertion.', 'An automated guess can preserve the wrong behavior.'),
  'manual/stlc': entry('A vehicle inspection has requirements, a plan, prepared equipment, checks, and a report.', 'STLC organizes testing work and the evidence it produces.', 'Testing activities can overlap and repeat rather than follow one fixed pass.', 'A tester receives a scoring change for review.', 'Analyze the rule, plan cases, prepare data, execute, and report.', 'Checks become understandable and repeatable.'),
  'manual/case': entry('A recipe specifies ingredients, actions, and the expected finished dish.', 'A test case records setup, inputs, actions, and expected results.', 'Unlike taste, the scoring expectation must be precise.', 'A second tester needs to reproduce the quiz check.', 'Provide the exact answer key, chosen answers, and expected percentage.', 'A repeatable case reduces misunderstanding.'),
  'manual/pattern': entry('Lay out ingredients, cook, check the dish, and clean the workspace.', 'Prepare, act, assert, and clean up separate responsibilities.', 'Cleaning a browser does not necessarily clean shared service data.', 'Several test runs create practice quiz results.', 'Set up known data, submit, compare, and remove only test-created data.', 'One test should not corrupt the next test.'),
  'manual/defect': entry('A useful repair note says which appliance failed, what you did, and what happened.', 'A defect report needs reproducible steps and expected versus actual results.', 'A report is evidence to investigate, not proof of the root cause.', 'A known 3/5 quiz displays 80%.', 'Record the build, answer data, steps, expected 60%, and observed 80%.', 'The team has enough context to reproduce the issue.'),
  'regression/definition': entry('After repairing a tap, check that nearby taps still work and no new leak appeared.', 'A software change can disturb behavior that already worked.', 'Software checks follow real dependencies; physical proximity is only an analogy.', 'A team changes quiz score rounding.', 'Check existing submission, score display, and other affected scoring cases.', 'Students should not lose working behavior when a new change arrives.'),
  'regression/confirmation': entry('Checking the repaired tap confirms the repair; checking other affected plumbing looks for side effects.', 'Confirmation targets the original defect; regression checks affected existing behavior.', 'The two activities can share a test case but have different purposes.', 'A fix corrects the 3/5 score from 80% to 60%.', 'Repeat 3/5, then check affected 0/5, 5/5, and other topic cases.', 'A successful fix can still have unwanted effects.'),
  'regression/impact': entry('Changing one train connection can affect several onward journeys.', 'Trace dependencies from the changed component.', 'Only the actual system can establish which dependencies exist.', 'A shared scoring function changes.', 'Trace its callers, displayed result, and any stored score.', 'Impact analysis guides relevant regression coverage.'),
  'regression/risk': entry('Before a journey, checking brakes matters more than polishing the bell.', 'Prioritize by likelihood, impact, and the affected behavior.', 'Risk judgments need product context rather than a universal ranking.', 'A release changes scoring and a decorative border.', 'Prioritize grading correctness while considering time and other risks.', 'Limited test time should address meaningful consequences.'),
  'regression/limits': entry('Checking several windows does not prove that every part of a house is sound.', 'Passing tests cover selected conditions.', 'Software test coverage is more complex than counting checked objects.', 'The scoring regression cases pass.', 'Report their scope and consider accessibility or exploratory checks separately.', 'A green result should not become an unlimited quality claim.'),
  'automation/why': entry('A dishwasher repeats a chosen cycle, but someone selects the load and checks whether the result is acceptable.', 'Automation executes instructions; people define the purpose and expectations.', 'Tests need explicit assertions and controlled data, not just repeated actions.', 'The same scoring checks are needed after frequent changes.', 'Encode known inputs and compare the calculated score with the agreed rule.', 'Repeatable checks can provide timely feedback.'),
  'automation/candidate': entry('A recurring bill is a better candidate for a standing instruction than a different one-off purchase each day.', 'Stable, frequent, controllable checks are useful automation candidates.', 'Value also depends on risk and maintenance cost.', 'The team repeats known percentage checks on every release.', 'Assess frequency, stability, data control, and expected result clarity.', 'Automating a useful check avoids spending effort on brittle low-value work.'),
  'automation/maintenance': entry('Directions to an office need updating when the entrance changes.', 'Test instructions may need revision when the interface or requirement changes.', 'Do not update expected results merely to hide a product defect.', 'A button is renamed after a reviewed design change.', 'Check the new interface and intent before updating its locator.', 'Maintained tests remain useful evidence.'),
  'automation/explore': entry('A checklist helps inspect a room, but a person may notice an unexpected smell or obstruction.', 'Exploration can discover questions outside scripted checks.', 'Exploration is purposeful learning, not random clicking.', 'All score checks pass, but feedback feels confusing.', 'Explore the learner journey and record new observations and risks.', 'Automation and human investigation address different needs.'),
  'assertions/meaning': entry('A receipt being printed does not mean the total on it is correct.', 'An assertion must check the required value, not merely its presence.', 'The expected value still needs an agreed rule.', 'A score label exists but shows 80% for the 3/5 fixture.', 'Compare the displayed value with 60%.', 'A weak assertion can let a serious defect pass.'),
  'assertions/state': entry('Comparing two recipes is unfair if one starts with different ingredients.', 'Known starting data makes outcomes interpretable.', 'A new browser session alone does not reset a shared database.', 'Two tests reuse a learner record with an old score.', 'Prepare isolated test records or reset the relevant data explicitly.', 'Hidden state can make tests pass or fail for the wrong reason.'),
  'assertions/wait': entry('Wait for the oven to reach the required temperature rather than assume it is ready after one minute.', 'Wait for a meaningful ready condition within a defined timeout.', 'The correct condition must still be chosen and verified.', 'A results screen loads at different speeds.', 'Wait for the relevant result to become ready, then assert its value.', 'Timing variation should not become a misleading test failure.'),
  'assertions/evidence': entry('A mechanic uses the warning reading, when it appeared, and what the driver was doing before replacing parts.', 'Tie screenshots, traces, logs, and inputs to the failing run.', 'Clues do not by themselves establish the root cause.', 'An overnight regression run reports expected 60%, actual 80%.', 'Inspect the answer fixture, application revision, screenshot, and trace before changing the test.', 'The cause could be the product, test, data, or environment.'),
  'tools/playwright': entry('A remote control sends actions; a checklist tells you what the screen should show.', 'Browser automation combines interactions with assertions.', 'The tool does not decide whether your business rule is correct.', 'A team wants repeatable quiz browser checks.', 'Use Playwright with real controls, known data, assertions, and run evidence.', 'The test must verify the student-visible outcome.'),
  'tools/cypress': entry('A workshop can use a different set of tools to inspect the same product.', 'Different browser tools can pursue the same quality objective.', 'Their APIs and execution models are not interchangeable.', 'A team considers Cypress for web checks.', 'Evaluate a real page or component against the same agreed behavior.', 'Choose tools that fit the project and maintainable checks.'),
  'tools/selenium': entry('A driver can receive instructions in different languages while controlling a vehicle.', 'Selenium provides browser control through language bindings.', 'Browser control still needs test structure, data, and assertions around it.', 'A Java-based team automates the quiz UI.', 'Use Selenium with a test framework and meaningful score assertions.', 'Language familiarity alone does not make a test correct.'),
  'tools/javascript': entry('Clear written instructions describe the order of steps in a task.', 'JavaScript expresses data, actions, and decisions in test code.', 'Programming syntax and asynchronous behavior need explicit learning.', 'A browser test stores an expected score and submits answers.', 'Read what each variable, function, and assertion contributes.', 'Students need language basics before copying automation code.'),
  'tools/node': entry('A recipe needs a kitchen in which to run; written instructions alone do not cook.', 'A runtime executes code; Node.js runs JavaScript outside the browser.', 'A runtime is software, not the programming language itself.', 'A student starts a JavaScript test runner from a terminal.', 'Distinguish runner-side execution from code running in the browser.', 'Knowing where code runs helps diagnose setup problems.'),
  'tools/npm': entry('A labeled shortcut performs the steps assigned to it, not whatever its name happens to suggest.', 'An npm script runs the command configured by the project.', 'npm also manages packages; it is not itself the entire testing framework.', 'A student runs npm test.', 'Read the test script and installed dependencies first.', 'The command only proves the checks it actually runs.'),
  'tools/git': entry('A document revision history lets a team compare what changed and restore context.', 'Git records revisions for collaboration and investigation.', 'A saved revision is not evidence that its tests passed.', 'A score starts failing after a code change.', 'Compare relevant commits and associate results with a revision.', 'History helps connect symptoms to candidate changes.'),
  'tools/pipeline': entry('A packing line follows configured stations and records their results.', 'A pipeline coordinates prepared steps and evidence.', 'An orchestrator does not invent the correct assertions.', 'A quiz change triggers a configured Jenkins job.', 'Identify the revision, install dependencies, run checks, and retain diagnostics.', 'Repeatable feedback supports release decisions.'),
  'tools/docker': entry('A packed tool kit brings known tools, but still needs a suitable workplace and supplies.', 'A container packages runtime dependencies.', 'It does not automatically include or reset all external data and configuration.', 'A test runner works locally but needs a repeatable execution environment.', 'Package the runtime and specify URLs, configuration, and data separately.', 'Repeatability depends on more than the image.'),
  'tools/kubernetes': entry('A coordinator assigns teams to work areas and replaces unavailable workers.', 'Orchestration manages running workloads and their availability.', 'It cannot judge whether a learner received the correct score.', 'An illustrative quiz service runs as container workloads.', 'Separate workload health from business-behavior checks.', 'Healthy infrastructure can still serve incorrect behavior.'),
  'tools/cloud': entry('Renting a workshop supplies space and utilities; you still decide what to build and inspect.', 'Cloud services provide infrastructure for an environment.', 'Using cloud services does not automatically configure secure or correct tests.', 'A team hosts a staging quiz service in AWS.', 'Target the intended environment with controlled data and configuration.', 'Tests must not accidentally operate against the wrong system.'),
  'ai/llm': entry('An autocomplete-like helper can propose convincing wording without verifying that the situation is real.', 'Generated language can be plausible and still wrong.', 'This is a limited intuition, not a complete explanation of how an LLM is trained.', 'An assistant suggests a quiz control that does not exist.', 'Verify the proposed details against the actual app.', 'Fluent output is not evidence of correctness.'),
  'ai/copilot': entry('A colleague drafts a checklist; the responsible reviewer checks it against the job.', 'An assistant can help draft tests while people review their correctness.', 'An AI assistant does not have a colleague\'s personal experience or accountability.', 'A tester asks Copilot for regression candidates.', 'Review each suggestion against requirements, real controls, and permitted data.', 'Assistance can speed drafting without replacing judgment.'),
  'ai/lms': entry('A library catalog organizes materials; a writing assistant helps draft text.', 'An LMS organizes learning; an LLM generates language.', 'A learning platform may include AI, but the terms still describe different roles.', 'A course team discusses learning delivery and AI support.', 'Identify which component manages participation and which generates a draft.', 'Clear terms prevent confusing platform needs with model capabilities.'),
  'ai/prompt': entry('A repair request is more useful when it includes the model, symptoms, and constraints.', 'Useful context helps an assistant produce a relevant draft.', 'A detailed prompt still cannot guarantee a correct answer.', 'A tester wants a draft score assertion.', 'Supply the agreed 3/5 rule, verified controls, fixture, and constraints.', 'Missing details should become questions rather than inventions.'),
  'ai/review': entry('A proofreader checks a draft against the original facts rather than trusting its neat formatting.', 'Review generated tests against the requirement and the real interface.', 'Review must include technical behavior, not only wording.', 'An AI draft only checks that score text exists.', 'Replace the weak check with the required value assertion after verifying the interface.', 'A polished test can still check the wrong thing.'),
  'ui/ui-layer': entry('Ordering at a kiosk includes pressing controls and reading the visible confirmation.', 'UI checks follow the user-facing interaction.', 'A visible result alone does not show which backend dependencies were exercised.', 'A learner chooses answers and submits a quiz.', 'Check that actual controls lead to the expected displayed result.', 'The service can work while the learner-facing flow fails.'),
  'ui/locator': entry('Finding a room by its name is often clearer than counting doors from a moving entrance.', 'A meaningful locator identifies the intended control.', 'Names can also change; locators must match the real interface.', 'A layout change moves the submit button.', 'Inspect its accessible role, name, or agreed test ID.', 'A locator should not depend unnecessarily on decoration or position.'),
  'ui/fixture': entry('To check a calculator, start with numbers whose answer you already know.', 'A controlled fixture makes the expected score defensible.', 'The fixture only covers its selected conditions.', 'An illustrative five-question key is A B C A B.', 'Submit A B C D E and establish that exactly three choices match.', 'The expected 60% is derived rather than guessed.'),
  'ui/ui-assert': entry('Check the amount on a receipt, not only that a receipt exists.', 'Verify the exact result the learner should see.', 'One displayed-value check does not cover every UI behavior.', 'The known 3/5 case reaches the results page.', 'Compare the displayed percentage with 60%.', 'A result can be visible and incorrect.'),
  'ui/diagnose': entry('A failed card payment might involve the card, terminal, connection, or account.', 'Investigate the layers involved in a failed check.', 'Do not assign a cause before examining evidence.', 'The UI check reports expected 60%, actual 80%.', 'Inspect input data, displayed text, trace, and the targeted application version.', 'Evidence guides the fix instead of weakening the assertion.'),
  'api/api-layer': entry('A waiter carries an order to the kitchen and brings back a response.', 'Programs exchange requests and responses through an agreed interface.', 'Real APIs have precise formats and failure behavior; the restaurant analogy is only a starting point.', 'A proposed scoring service receives quiz answers from a client.', 'Check the request contract and direct response independently of the screen.', 'A service error and a display error require different checks.'),
  'api/request': entry('An order ticket specifies what was ordered and the relevant details.', 'A request carries contract-defined inputs.', 'A method, path, headers, and body have technical meaning beyond an order ticket.', 'A proposed API accepts a quiz ID and answer choices.', 'Verify required inputs and agreed invalid-input behavior.', 'The service needs unambiguous inputs before its output can be judged.'),
  'api/response': entry('A parcel marked delivered can still contain the wrong item.', 'A successful status alone does not establish correct business data.', 'HTTP status meanings must be interpreted using the actual contract.', 'The hypothetical response is HTTP 200 but percentage is 80 for the 3/5 fixture.', 'Check the contract-defined status, fields, and expected 60% separately.', 'Transport success and business correctness are different claims.'),
  'api/karate': entry('A checklist compares a returned delivery with its agreed contents.', 'Karate expresses requests and response expectations.', 'The framework still needs a real service URL, fixtures, and environment.', 'A team prepares API regression checks for a future scoring endpoint.', 'Review status and score assertions against the implemented contract before running.', 'A code excerpt does not establish that a runnable lab exists.'),
  'api/combine': entry('Checking both a kitchen order and the served plate helps locate whether preparation or delivery went wrong.', 'UI and API checks provide evidence about different parts of the journey.', 'The exact boundaries depend on what each test really exercises or simulates.', 'A proposed service returns 60%, but the page displays 80%.', 'Compare direct service evidence with browser rendering evidence.', 'The two views can help locate the mismatch and its user impact.')
};

// Observed local build cases; detailed provenance is retained in instructor notes.
export const projectCases = {
  'assertions/evidence': {
    situation:'During this academy build, the curriculum PDF downloaded correctly, but the browser preview showed a blank panel.',
    check:'The download check established that the file was correct. Inspecting the rendered page revealed that the reading experience was still broken.',
    resolution:'The preview was changed to locally rendered document pages with page navigation and zoom. The later check verified all 54 page assets and the visible preview.',
    lesson:'Evidence must match the user need: a valid file and a readable preview are different outcomes.'
  },
  'assertions/wait': {
    situation:'A Class 1 browser check read the previous card title just after the URL had changed to the next card.',
    check:'Waiting only for the URL change did not establish that the requested card had finished rendering.',
    resolution:'The check was updated to wait for the expected card heading before reading it. The guided-route check then passed.',
    lesson:'Wait for the condition you actually need. This was a test-synchronization issue, not evidence that the concept content was wrong.'
  }
};

export const classOne = {
  sdlc: {cards:['lifecycle','quality'], takeaway:'Quality starts before coding and continues after release.', later:'Course module 02 develops SDLC and early-assurance practice.', question:['Where should the team resolve an unclear scoring rule?',['Only after release','During early requirement review','Only after writing automation'],1,'Clarify expected behavior early; automation depends on that agreement.','quality']},
  requirements: {cards:['rule'], takeaway:'A test needs an agreed, measurable expectation.', later:'Course modules 02 and 04 connect requirements to coverage.', question:['For five equally weighted questions, three correct answers should display…',['60%','Any visible score','The most recent score'],0,'3 divided by 5 times 100 gives the expected 60%.','rule']},
  manual: {cards:['stlc','case'], takeaway:'Manual test design explains what automation must check.', later:'Course modules 03–05 develop test planning, cases, execution, and defects.', question:['What makes a score check repeatable?',['A vague instruction to try it','Known inputs, actions, and an expected result','A screenshot without context'],1,'A test case connects controlled setup and actions to a defensible expected outcome.','case']},
  regression: {cards:['definition','confirmation'], takeaway:'After a change, check the fix and affected existing behavior.', later:'Course modules 04, 05, and 10 develop risk-based regression coverage.', question:['After confirming a repaired scoring case, why check another affected topic?',['To look for side effects','To change the requirement','To prove all defects are gone'],0,'Regression testing looks for adverse effects on existing behavior.','confirmation']},
  automation: {cards:['why','candidate'], takeaway:'Automate valuable repeatable checks with clear expectations.', later:'Course modules 09–11 develop browser and API automation.', question:['Which is a useful automation candidate?',['An undefined rule','A frequently repeated, controlled scoring check','An assertion that always passes'],1,'Frequency, clear expectations, controllable data, and value support a useful candidate.','candidate']},
  assertions: {cards:['meaning','evidence'], takeaway:'Check the right value, then investigate evidence when it differs.', later:'Course modules 05 and 09–11 develop assertions and diagnosis.', question:['The score exists but is 80% instead of the expected 60%. What matters?',['Only that the label exists','The mismatch and the evidence from this run','Making the test green by changing 60 to 80'],1,'Compare with the agreed rule and investigate the product, test, data, and environment.','evidence']},
  tools: {cards:['playwright','cypress','selenium'], takeaway:'Recognize tool roles; the quality objective stays the same.', later:'Course modules 08–12 cover setup and toolchains. JavaScript, Node.js, and npm support the JavaScript tools; Jenkins, Docker, cloud, and service workflows connect later.', question:['What do Playwright, Cypress, and Selenium still need from us?',['Only a tool name','Real interface details, test design, data, and assertions','Permission to invent the expected result'],1,'A tool executes a designed check; it does not define correctness for the product.','playwright']},
  ai: {cards:['copilot','review'], takeaway:'Use AI for reviewed drafts, with requirements as the anchor.', later:'Course modules 14–15 develop LLM/Copilot foundations and AI-assisted test engineering.', question:['An AI draft checks only that score text exists. What should the tester do?',['Trust the fluent draft','Review it against the required value and real interface','Assume it was already executed'],1,'The generated draft needs human review and evidence from actual execution.','review']},
  ui: {cards:['ui-layer','ui-assert'], takeaway:'UI automation checks the interaction and result the student sees.', later:'Course module 09 develops browser automation on implemented website controls.', question:['Which outcome belongs to a UI score check?',['The required percentage is displayed after the interaction','A service is running somewhere','A test file has a name'],0,'The browser check must connect the user action to its visible business result.','ui-assert']},
  api: {cards:['api-layer','response','karate','combine'], takeaway:'API checks inspect the service contract; combine them with UI evidence.', later:'Course modules 06 and 11 develop APIs and Karate. Hands-on work needs an implemented endpoint and controlled data.', question:['A proposed API returns 60%, but the page shows 80%. What does this suggest?',['Every layer passed','Investigate the display path using UI and service evidence','Change the expected score to 80%'],1,'Correct service data does not prove that the page renders it correctly.','combine']}
};
