import {lessonFor} from './visual-lessons.js';
import {materials} from './concept-materials.js';
import {conceptDiagram,conceptMindMap} from './concept-diagrams.js';
import {readingPanel,bindReading,relationshipLinks} from './concept-reading.js';
import {examplePanel,bindExamples} from './lesson-examples.js';
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
export function openVisualLesson(mod,card,opener){
 const model=lessonFor(mod,card);let active=model.initial||0,view='read',revealed=false,zoom=100;
 const dialog=document.createElement('dialog');dialog.className='visual-dialog';dialog.setAttribute('aria-labelledby','visual-title');document.body.append(dialog);
 function content(){
  if(view==='read')return readingPanel(mod,card);
  const material=materials[`${mod.id}/${card.id}`];
  if(view==='svg')return `<p class="visual-label">Concept diagram · ${esc(material.title)}</p><div class="visual-diagram" tabindex="0" role="region" aria-label="Scrollable concept diagram">${conceptDiagram(`${mod.id}/${card.id}`)}</div><p class="study-caption">Scoring values and system designs are illustrative unless explicitly described as observed. On a small screen, scroll across to read the diagram at full size.</p><ol class="study-notes">${material.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><details class="diagram-text"><summary>Read the diagram as text</summary><ul>${material.items.map(x=>`<li><strong>${esc(x[0])}:</strong> ${esc(x.slice(1).join('. '))}</li>`).join('')}</ul></details>`;
  if(view==='whimsical')return `<p class="visual-label">Concept mind map · ${esc(card.title)}</p><div class="visual-diagram" tabindex="0" role="region" aria-label="Scrollable concept mind map">${conceptMindMap(mod,card)}</div><p class="study-caption">Follow a relationship to study a related concept in the full library.</p>${relationshipLinks(mod,card)}<details class="whimsical-overview"><summary>Open the Whimsical topic overview<small>Broader context for ${esc(mod.title)}</small></summary><div class="map-tools"><button id="map-out" aria-label="Zoom out mind map" ${zoom<=100?'disabled':''}>−</button><output aria-live="polite">${zoom}%</output><button id="map-in" aria-label="Zoom in mind map" ${zoom>=250?'disabled':''}>+</button><span>Scroll the white canvas to explore</span></div><div class="whimsical-canvas" tabindex="0" role="region" aria-label="Scrollable Whimsical map of ${esc(mod.title)}"><img src="assets/whimsical/${mod.id==='sdlc'?'sdlc-stages':mod.id==='manual'?'manual-stages':mod.id}.png" alt="Whimsical topic map for ${esc(mod.title)}" style="width:${zoom}%;min-width:${zoom*8}px"></div><details class="map-text"><summary>Read the topic connections as text</summary><ul>${mod.cards.map(x=>`<li><strong>${esc(x.title)}</strong>: ${esc(x.idea)}</li>`).join('')}</ul></details></details>`;
  const node=model.nodes[active];return `<p class="visual-label">Interactive lesson · choose a step, reveal one idea</p><div class="visual-nodes" role="group" aria-label="Choose a visual step">${model.nodes.map((x,i)=>`<button data-node="${i}" aria-pressed="${i===active}">${i+1}. ${esc(x[0])}</button>`).join('')}</div><section class="visual-detail interactive-focus" aria-live="polite"><p class="eyebrow">${active+1} / ${model.nodes.length}</p><h3>${esc(node[1])}</h3>${model.kind==='focus'&&active===2&&!revealed?'<button id="visual-reveal">Reveal recall answer</button>':`<p>${esc(node[2])}</p>`}${card.code&&model.kind==='focus'&&active===1?`<pre><code>${esc(card.code)}</code></pre>`:''}</section><div class="interactive-controls"><button id="visual-prev" ${active===0?'disabled':''}>← Previous step</button><button id="visual-next">${active===model.nodes.length-1?'Restart this lesson':'Next step →'}</button></div><p class="small">Illustrative lesson. This does not execute a live API request or an automation test.</p>`;
 }
 function render(){dialog.innerHTML=`<div class="visual-header"><div><p class="eyebrow">${esc(mod.title)} · concept material</p><h2 id="visual-title">${esc(card.title)}</h2></div><button id="visual-close" aria-label="Close visual lesson">✕</button></div><div class="material-tabs" role="group" aria-label="Choose learning material"><button data-view="read" aria-pressed="${view==='read'}">1 · Read</button><button data-view="svg" aria-pressed="${view==='svg'}">2 · Concept diagram</button><button data-view="whimsical" aria-pressed="${view==='whimsical'}">3 · Mind map</button><button data-view="interactive" aria-pressed="${view==='interactive'}">4 · Interactive</button></div><div class="visual-body material-content">${content()}</div><div class="visual-footer"><span>One concept · four ways to study</span><button id="visual-done">Return to concept card</button></div>`;
  const context=document.createElement('details');context.className='visual-case';context.innerHTML=`<summary>Connect this visual to a practical example</summary>${examplePanel(mod,card)}`;dialog.querySelector('.visual-body').append(context);bindExamples(context,mod,card);
  bindReading(dialog,mod,card);
  dialog.querySelectorAll('.concept-links a').forEach(a=>a.addEventListener('click',()=>dialog.close()));
  dialog.querySelector('#visual-close').onclick=()=>dialog.close();dialog.querySelector('#visual-done').onclick=()=>dialog.close();
  dialog.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();dialog.querySelector(`[data-view="${view}"]`).focus();});
  dialog.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{active=Number(b.dataset.node);revealed=false;render();dialog.querySelector(`[data-node="${active}"]`).focus();});
  const prev=dialog.querySelector('#visual-prev'),next=dialog.querySelector('#visual-next'),reveal=dialog.querySelector('#visual-reveal');
  if(prev)prev.onclick=()=>{active--;revealed=false;render();dialog.querySelector('#visual-next').focus();};
  if(next)next.onclick=()=>{active=(active+1)%model.nodes.length;revealed=false;render();dialog.querySelector('#visual-next').focus();};
  if(reveal)reveal.onclick=()=>{revealed=true;render();dialog.querySelector('#visual-next').focus();};
  for(const [id,delta]of [['map-out',-25],['map-in',25]]){const button=dialog.querySelector('#'+id);if(button)button.onclick=()=>{zoom=Math.max(100,Math.min(250,zoom+delta));render();dialog.querySelector('.whimsical-overview').open=true;dialog.querySelector('#'+id).focus();};}
 }
 dialog.addEventListener('close',()=>{dialog.remove();opener?.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});render();dialog.showModal();dialog.querySelector('#visual-close').focus();
}
