import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Status='open'|'in_progress'|'resolved';
type Ticket={id:string;title:string;student:string;description:string;status:Status;createdAt:string;updatedAt:string};
const labels:Record<Status,string>={open:'Open',in_progress:'In progress',resolved:'Resolved'};
async function api<T>(path:string,options:RequestInit={}):Promise<T>{
 const response=await fetch(new URL('api/'+path,document.baseURI),{...options,headers:{'Content-Type':'application/json',...options.headers}});
 const result=await response.json();if(!response.ok)throw new Error(result.error||`Request failed (${response.status})`);return result;
}
function App(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[labMode,setLabMode]=useState(false);
 const [form,setForm]=useState({student:'',title:'',description:''}),[formErrors,setFormErrors]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false);
 const [selected,setSelected]=useState<Ticket|null>(null),[nextStatus,setNextStatus]=useState<Status>('open');
 const detailDialog=useRef<HTMLDialogElement>(null),resetDialog=useRef<HTMLDialogElement>(null),lastTrigger=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{api<{labMode:boolean}>('health').then(data=>setLabMode(data.labMode===true)).catch(()=>{});},[]);
 useEffect(()=>{
  let active=true;const abort=new AbortController();setLoading(true);setError('');
  const timer=setTimeout(()=>{const params=new URLSearchParams({q:query});if(filter)params.set('status',filter);
   api<{tickets:Ticket[]}>('tickets?'+params,{signal:abort.signal}).then(data=>{if(active)setTickets(data.tickets)}).catch(err=>{if(active&&err.name!=='AbortError')setError(err.message)}).finally(()=>{if(active)setLoading(false)});
  },300);return()=>{active=false;clearTimeout(timer);abort.abort()};
 },[query,filter,revision]);
 useEffect(()=>{if(selected&&!detailDialog.current?.open)detailDialog.current?.showModal();},[selected]);
 function closeDetails(){detailDialog.current?.close();setSelected(null);lastTrigger.current?.focus()}
 async function createTicket(event:React.FormEvent){
  event.preventDefault();setNotice('');setError('');const errors:Record<string,string>={};
  for(const [key,value] of Object.entries(form)){const max=key==='description'?500:120;if(value.trim().length<3||value.trim().length>max)errors[key]=`${key==='student'?'Your name':key==='title'?'Title':'Description'} must contain 3–${max} characters.`;}
  setFormErrors(errors);if(Object.keys(errors).length)return;setSaving(true);
  try{const data=await api<{ticket:Ticket}>('tickets',{method:'POST',body:JSON.stringify(form)});setForm({student:'',title:'',description:''});setQuery('');setFilter('');setNotice(`Ticket created: ${data.ticket.title}. Status: Open.`);setRevision(n=>n+1)}catch(err){setError((err as Error).message)}finally{setSaving(false)}
 }
 async function updateStatus(){if(!selected)return;setSaving(true);setError('');try{const data=await api<{ticket:Ticket}>('tickets/'+encodeURIComponent(selected.id),{method:'PATCH',body:JSON.stringify({status:nextStatus})});setNotice(`Status updated to ${labels[data.ticket.status]} for ${data.ticket.title}.`);closeDetails();setRevision(n=>n+1)}catch(err){setError((err as Error).message)}finally{setSaving(false)}}
 async function reset(){setSaving(true);try{await api('test/reset',{method:'POST',body:'{}'});setQuery('');setFilter('');setNotice('Practice records reset. Three example tickets restored.');setError('');setRevision(n=>n+1);resetDialog.current?.close()}catch(err){setError((err as Error).message)}finally{setSaving(false)}}
 const local=['127.0.0.1','localhost'].includes(location.hostname);
 const academy=local?`http://${location.hostname}:53217/automation.html`:'https://jzscodegame.github.io/SDLC---STLC/';
 return <><header className="topbar"><a className="brand" href={academy}><span>mq</span>Mini Quiz <strong>Tech &amp; AI Academy</strong></a><a className="back" href={academy}>← Back to academy</a></header>
 <main><div className="breadcrumb">CLASS 2 <span>/</span> UI &amp; API automation practice</div><section className="hero"><div><p className="eyebrow">YOUR CLASSROOM TEST APPLICATION</p><h1>Academy Help Desk<span>Real interactions.<br/>Repeatable checks.</span></h1><p>Create a ticket, change its status, and find it again. This is the same workflow your automated tests will check.</p></div><aside className="scenario"><p className="eyebrow">TODAY’S REQUIREMENT</p><h2>A new ticket starts as Open.</h2><ol><li>Enter a title, your name, and a description.</li><li>Create the ticket.</li><li>Verify its title and Open status in the list.</li></ol><p className="small">Classroom practice only. These tickets are not real support requests.</p></aside></section>
 {notice&&<div className="notice" role="status">{notice}</div>}{error&&<div className="error" role="alert">{error}</div>}
 <div className="workspace"><section className="panel new-ticket"><p className="eyebrow">01 / CREATE</p><h2>Tell us what happened.</h2><p className="muted">Use a fictional student name and practice details.</p><form onSubmit={createTicket} noValidate>
 {(['student','title','description'] as const).map(key=><div className="field" key={key}><label htmlFor={key}>{key==='student'?'Your name':key==='title'?'Title':'Description'} <span className="required">required</span></label>{key==='description'?<textarea id={key} rows={4} maxLength={500} value={form[key]} aria-invalid={!!formErrors[key]} aria-describedby={formErrors[key]?key+'-error':undefined} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input id={key} maxLength={120} value={form[key]} aria-invalid={!!formErrors[key]} aria-describedby={formErrors[key]?key+'-error':undefined} onChange={e=>setForm({...form,[key]:e.target.value})}/>} {formErrors[key]&&<p id={key+'-error'} className="field-error" role="alert">{formErrors[key]}</p>}</div>)}
 <button className="primary" type="submit" disabled={saving}>{saving?'Saving…':'Create ticket'}</button></form><p className="small">All fields need at least 3 characters. Names and titles allow 120; descriptions allow 500.</p></section>
 <section className="tickets-section" aria-labelledby="tickets-heading"><div className="section-heading"><div><p className="eyebrow">02 / FIND &amp; VERIFY</p><h2 id="tickets-heading">Your tickets</h2></div><span className="count" data-testid="ticket-count">{loading?'…':tickets.length}</span></div><div className="filters"><div><label htmlFor="search">Search tickets</label><input id="search" type="search" placeholder="Search title, name, or description" value={query} onChange={e=>setQuery(e.target.value)}/></div><div><label htmlFor="status-filter">Filter by status</label><select id="status-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></div>
 <div className="ticket-list" aria-busy={loading}>{loading?<p className="empty" role="status">Searching tickets…</p>:tickets.length===0?<div className="empty"><h3>No matching tickets</h3><p>Change your search or choose All statuses.</p></div>:tickets.map(ticket=><button className="ticket" key={ticket.id} data-testid={'ticket-'+ticket.id} onClick={e=>{lastTrigger.current=e.currentTarget;setSelected(ticket);setNextStatus(ticket.status)}}><span className="ticket-meta"><span>{ticket.id}</span><span className={'badge '+ticket.status}>{labels[ticket.status]}</span></span><strong>{ticket.title}</strong><span className="ticket-description">{ticket.description}</span><span className="ticket-bottom">{ticket.student}<span>View &amp; update →</span></span></button>)}</div>
 <p className="small">Search waits briefly before fetching results. Tests should wait for the expected ticket, not a fixed sleep.</p>{labMode&&<button className="text-button" type="button" onClick={()=>resetDialog.current?.showModal()}>Reset practice records</button>}</section></div>
 <section className="exercise"><p className="eyebrow">03 / AUTOMATE</p><h2>Repeat the same check with code.</h2><div><article><h3>Playwright</h3><p>Use labels and roles to locate the form. Assert that the new ticket appears.</p><code>npm run test:playwright</code></article><article><h3>Cypress</h3><p>Repeat the workflow and compare the assertions and failure messages.</p><code>npm run test:cypress</code></article></div><p className="small">Run commands in your repository terminal. These examples do not execute from this page. Run suites one at a time; they reset this workspace’s practice records.</p></section>
 <footer>Mini Quiz Tech &amp; AI Academy <span>Practice data is separate from your academy quiz scores.</span></footer></main>
 <dialog ref={detailDialog} aria-labelledby="detail-title" onCancel={()=>setSelected(null)}>{selected&&<><p className="eyebrow">{selected.id} · TICKET DETAILS</p><h2 id="detail-title">{selected.title}</h2><p className="muted">Submitted by {selected.student}</p><p className="description">{selected.description}</p><label htmlFor="edit-status">Ticket status</label><select id="edit-status" value={nextStatus} onChange={e=>setNextStatus(e.target.value as Status)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><div className="dialog-actions"><button type="button" onClick={closeDetails}>Cancel</button><button className="primary" type="button" disabled={saving} onClick={updateStatus}>Save status</button></div></>}</dialog>
 <dialog ref={resetDialog} aria-labelledby="reset-title"><p className="eyebrow">START AGAIN</p><h2 id="reset-title">Reset practice records?</h2><p>This deletes tickets you created in this practice app and restores the three example tickets. Your academy quiz scores are unaffected.</p><div className="dialog-actions"><button type="button" onClick={()=>resetDialog.current?.close()}>Cancel</button><button className="primary" type="button" disabled={saving} onClick={reset}>Confirm reset</button></div></dialog>
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
